### ISSUE TITLE
iou for foreground segmentation woth pointnet++

### ISSUE THREAD

**Issue by bigsheep2012** [sshaoshuai/PointRCNN#30]
Hello Shaoshuai @sshaoshuai ,

Thanks for sharing this excellent work.
May I know the iou value you can achieve for the foreground segmentation with pointnet++, which is one of the key task in the entire PointRCNN framework (for car detection with focal loss). 

Thanks in advance.

**Comment by sshaoshuai** [comment]
The foreground IoU on validation set could achieve about 65%~70%, which is sensitive to the score thresh for foreground points. Also, since there are some random point sampling operations of PointNet++, the value is not stable, and we only the the foreground score to rank and select the 3D proposals. BTW, the visualization of  foreground segmentation results is good and you could use mayavi to visualize it.
