### ISSUE TITLE
The effectiveness of GT_AUG?

### ISSUE THREAD

**Issue by RobertAuditore** [sshaoshuai/PointRCNN#55]
@sshaoshuai , will GT_AUG increase the result greatly? I am a little bit confused about GT_AUG, since the gt-bboxes and inside points from other scenes do not have the same point distribution of current scene. For example, a gtbox with inside points is put in the shadow of a car in the current scene, where no points should appears.

**Comment by sshaoshuai** [comment]
`GT_AUG` is important for the performance on KITTI dataset since the training samples of KITTI dataset are relatively small. 
You are right, `GT_AUG` will destroy the far-away context information and introduce more noise to the dataset, but it could simulate more situations and could also balance the number of positive samples and negative samples in the scene, and finally the performance got improved.
